config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'filter_home#index'
  devise_for :users
    
  scope '/admin' do
    get '/', to: 'welcome#index'
    
    
    
    
    
    
    get :zip_images, to: 'image_zip#zip_images'
    get :download_zipped_images, to: 'image_zip#download_zip'
    # post '/sites/csv/results', to: 'csv#results', as: :results
  end
  
  # todo - will slowly be moving controllers from scope to namespace
  namespace :admin do
    resources :bulk_upload, only: [:index, :create]
    resources :drop_upload, only: [:index, :create]
    resources :results
    resources :types
    resources :site_groups
    resources :submissions
    resources :report_upload
    resources :sites do
      resources :submissions
      resources :registrations
    end

    # reporting
    get :participant_report, to: 'csv#participant_report'
    get :basic_submission_report, to: 'csv#basic_submission'
    get :site_specific_time_period_report, to: 'csv#site_specific_time_period'
    get :site_specific_tags_report, to: 'csv#site_specific_tags'
    get :tag_specific_report, to: 'csv#tags_report'
    get :image_quality_report, to: 'csv#image_quality'
  end
  
  # API  
  namespace :api do
    namespace :v1 do
      resources :submissions
      get :submission_data, to: 'submissions#data'
      get :zip_images, to: 'zip#zip_images'
    end
  end
end

app/controllers/admin/results_controller.rb
class Admin::ResultsController < ApplicationController

  def index
    @submissions = Submission.count
  end
  


  private
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def index
    @type_numbers = create_type_numbers_array
    # @site_numbers = create_site_numbers
  end
  


  private

  def create_type_numbers_array
    Type::NAMES.map do |name|
      Submission.joins(:type).where(types: { name: name }).count
    end
  end

  def create_site_numbers
    Site.all.map do |site|
      {
        name: site.name, 
        submissions: site.submissions.count,
        twitter: site.submissions.joins(:type).where(types: { name: "TWITTER" }).count,
        instagram: site.submissions.joins(:type).where(types: { name: "INSTAGRAM" }).count,
        email: site.submissions.joins(:type).where(types: { name: "EMAIL" }).count,
        whatsapp: site.submissions.joins(:type).where(types: { name: "WHATSAPP" }).count
      }
    end
  end
end

app/views/admin/results/index.html.erb
<h2 id="csv-reports">Current total of submissions: <b><%= @submissions %></b></h2>

<div class="mt6 mb6">
  <h4>Submission report</h4>
  <div class="mb3">
    This report returns a list of all submissions with with site name, site group, record taken and the image URL. 
  </div>
  <div>
    <%= link_to 'Basic submission report', admin_basic_submission_report_path(format: "csv"), class: 'button' %>
  </div>
</div>

<h3>Customise reports</h3>
<div class="flex column mb6">
  <div class="w-50">
    <p>
      From date:
        <%= date_field_tag(:from_date, Date.today - 1.week, class: 'from-date mb4') %><br/>
      To date:
        <%= date_field_tag(:from_date, Date.today, class: 'to-date mb4') %><br/>
      Choose site: 
        <%= select_tag :site_id, options_for_select(Site.all.collect { | site | [site.name, site.id] }),  :include_blank => true, class: 'site-select mb4'%><br/>
      
      <% tags = ActsAsTaggableOn::Tag.all.map {|t| t.name}.uniq %>
      Choose tag: 
        <%= select_tag :tag, options_for_select(tags), :include_blank => true, class: 'tag-select mb4'%>
    </p>
  </div>
  
  <div class="w-50">
    <span class="db pb4">
      <%= link_to 'Site specific with submission patterns',  admin_site_specific_time_period_report_path(format: "csv", ), class: 'button', id: 'site-specific-report' %><br/>
      Creates a report of each day in the selected time frame, showing how many submissions and participants
      each day for any given site. Should only be generated for short timeframes.
    </span>

    <span class="db pb4">
      <%= link_to 'Site specific with tags',  admin_site_specific_tags_report_path(format: "csv", ), class: 'button', id: 'site-specific-tag-report' %><br/>
      Returns list submissions for a selected site alongside any given tags.
    </span>

    <span class="db pb4">
      <%= link_to 'Tag specific report',  admin_tag_specific_report_path(format: "csv"), class: 'button', id: 'manual-tag-report' %><br/>
      Create report listing submissions with specified tag, or submissions with specified tag for a specific site.
    </span>

  </div>
</div>

<h3>Other reports</h3>
<div class="flex column mb6">
  <div class="w-50">
    <h4>Participant report</h4>
      <%= link_to 'Participant report', admin_participant_report_path(format: "csv"), class: 'button' %>
  </div>

  <div class="w-50">
    <h4>Image quality</h4>

    <%= link_to 'instagram report', admin_image_quality_report_path(format: "csv", type_name: 'INSTAGRAM'), class: 'button'  %>
    <%= link_to 'twitter report', admin_image_quality_report_path(format: "csv", type_name: 'TWITTER'), class: 'button'  %>
    <%= link_to 'email report', admin_image_quality_report_path(format: "csv", type_name: 'EMAIL'), class: 'button'  %>
    <%= link_to 'whatsapp report', admin_image_quality_report_path(format: "csv", type_name: 'WHATSAPP'), class: 'button'  %>
  </div>
</div>


<h3>Zip images</h3>
<div class="flex flex-wrap column justify-between">
  <div class="w-50">
    <h4>Create new zip</h4>
    <p class="w-60-l">
      This will compress all the images for a given site, submitted up to now, and send the link to the given email address. 
      <strong>This will take a while!</strong>
    </p>
    <%= form_tag("/admin/zip_images", method: "get") do %>
      <%= select_tag :site_id, options_for_select(Site.all.collect { | site | [site.name, site.id] }),  :include_blank => true %><br/>
      <%= text_field :email, nil,  placeholder: "Email address" %> <br/>
      <%= submit_tag("Collect and email zipped images") %>
    <% end %>
  </div>

  <div class="w-50">  
    <h4>Download current zip</h4>    
      <p class="w-60-l">
        This will find the latest compressed file for a given site, and download them.
        This is much quicker than creating one from scratch! 
        If no compressed file is present, you will need to create one using the form to the left.
      </p>
      <%= form_tag("/admin/download_zipped_images", method: "get") do %>
        <%= select_tag :site_id, options_for_select(Site.all.collect { | site | [site.name, site.id] }),  :include_blank => true %><br/>
        <%= submit_tag("Collect and download zipped images") %>
      <% end %>

  </div>
</div>