config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'filter_home#index'
  devise_for :users
    
  scope '/admin' do
    get '/', to: 'welcome#index'
    
    
    
    
    
    
    get :zip_images, to: 'image_zip#zip_images'
    get :download_zipped_images, to: 'image_zip#download_zip'
    # post '/sites/csv/results', to: 'csv#results', as: :results
  end
  
  # todo - will slowly be moving controllers from scope to namespace
  namespace :admin do
    resources :bulk_upload, only: [:index, :create]
    resources :drop_upload, only: [:index, :create]
    resources :results
    resources :types
    resources :site_groups
    resources :submissions
    resources :report_upload
    resources :sites do
      resources :submissions
      resources :registrations
    end

    # reporting
    get :participant_report, to: 'csv#participant_report'
    get :basic_submission_report, to: 'csv#basic_submission'
    get :site_specific_time_period_report, to: 'csv#site_specific_time_period'
    get :site_specific_tags_report, to: 'csv#site_specific_tags'
    get :tag_specific_report, to: 'csv#tags_report'
    get :image_quality_report, to: 'csv#image_quality'
  end
  
  # API  
  namespace :api do
    namespace :v1 do
      resources :submissions
      get :submission_data, to: 'submissions#data'
      get :zip_images, to: 'zip#zip_images'
    end
  end
end

app/controllers/admin/types_controller.rb
class Admin::TypesController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper

  before_action :redirect_unless_admin
  before_action :set_type, only: [:show, :edit, :update, :destroy]
  
  def index
    @types = Type.all
  end
  
  def new
    @type = Type.new
  end

  def create
    @type = Type.new(type_params)
  end

  def update
    @type.update_attributes(type_params)
  end

  def destroy
    @type.destroy
  end

  private
  def set_type
    @type = Type.find(params[:id])
  end

  def type_params
    params.require(:type).permit(:id, :name, :data)
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper

  before_action :redirect_unless_admin
  before_action :set_type, only: [:show, :edit, :update, :destroy]
  
  def index
    @types = Type.all
  end
  
  def new
    @type = Type.new
  end

  def create
    @type = Type.new(type_params)
  end

  def update
    @type.update_attributes(type_params)
  end

  def destroy
    @type.destroy
  end

  private
  def set_type
    @type = Type.find(params[:id])
  end

  def type_params
    params.require(:type).permit(:id, :name, :data)
  end
end

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Types</h1>

<table>
  <thead>
    <tr>
      <th colspan="1">Data</th>
      <th colspan="1">Comment</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <% data = type.data.map {|a,b| "#{a}: #{b}" if b.present?} %>
        <td><%=data.compact[0] %></td>
        <td><%=type.comment %></td>

        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>