config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'filter_home#index'
  devise_for :users
    
  scope '/admin' do
    get '/', to: 'welcome#index'
    
    
    
    
    
    
    get :zip_images, to: 'image_zip#zip_images'
    get :download_zipped_images, to: 'image_zip#download_zip'
    # post '/sites/csv/results', to: 'csv#results', as: :results
  end
  
  # todo - will slowly be moving controllers from scope to namespace
  namespace :admin do
    resources :bulk_upload, only: [:index, :create]
    resources :drop_upload, only: [:index, :create]
    resources :results
    resources :types
    resources :site_groups
    resources :submissions
    resources :report_upload
    resources :sites do
      resources :submissions
      resources :registrations
    end

    # reporting
    get :participant_report, to: 'csv#participant_report'
    get :basic_submission_report, to: 'csv#basic_submission'
    get :site_specific_time_period_report, to: 'csv#site_specific_time_period'
    get :site_specific_tags_report, to: 'csv#site_specific_tags'
    get :tag_specific_report, to: 'csv#tags_report'
    get :image_quality_report, to: 'csv#image_quality'
  end
  
  # API  
  namespace :api do
    namespace :v1 do
      resources :submissions
      get :submission_data, to: 'submissions#data'
      get :zip_images, to: 'zip#zip_images'
    end
  end
end

app/models/site_group.rb
class SiteGroup < ApplicationRecord
  has_many :sites
end

app/controllers/admin/site_groups_controller.rb
class Admin::SiteGroupsController < ApplicationController
  before_action :redirect_unless_admin

  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper

  before_action :set_site_group, only: [:show, :edit, :update, :destroy]
  
  def index
    @site_groups = SiteGroup.all.includes([:sites])
  end
  
  def new
    @site_group = SiteGroup.new
  end

  def create
    @site_group = SiteGroup.new(site_group_params)
    if @site_group.save
      redirect_to admin_site_groups_path
    else
      render 'new'
    end
  end

  def update
    @site_group.update(site_group_params)
    if @site_group.save
      redirect_to admin_site_groups_path
    else
      render 'edit'
    end
  end

  def show
    @sites = @site_group.sites
  end

  def destroy
    if @site_group.sites.present?
      flash[:notice] = 'Cannot delete a site group that has associated sites'
      redirect_to admin_site_groups_path
    else
      @site_group.destroy
      redirect_to admin_site_groups_path
    end
  end


  private
  def set_site_group
    @site_group = SiteGroup.find(params[:id])
  end

  def site_group_params
    params.require(:site_group).permit(:name, :identifier)
  end
end

app/views/admin/site_groups/_form.html.erb
<% if @site_group && @site_group.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@site_group.errors.count, "error") %> prohibited this site_group from being saved:</h2>

    <ul>
    <% @site_group.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class='row'>
  <div class="col">
    <%= form.label :name, "Site Group Name"%>
  </div>
  <div class="col">
    <%= form.text_field :name, id: :name %>
  </div>
</div>

<div class="row">
  <div class="col">
    <%= form.label :identifier, "Identifier (PIC number)"%>
  </div>
  <div class="col">
    <%= form.text_field :identifier, step: :any %>
  </div>
</div>


<div class="actions">
  <%= form.submit %>
</div>

app/views/admin/site_groups/edit.html.erb
<h1>Editing Site Group</h1>

<%= form_with(model: @site_group, local: true, url: admin_site_group_path) do |form| %>
  <%= render 'form', form: form, site_group: @site_group %>
<% end %>

<%= link_to 'Show', admin_site_group_path(@site_group) %> |
<%= link_to 'Back', admin_site_groups_path %>

app/views/admin/site_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Site Groups</h1>
<% if @site_groups.present? %>
  <div class="mw9 center ph3-ns">
      <div class="cf ph2-ns pv2 mv2 ">
        <div class="fl w-10 pa2 b">
          Name
        </div>
        <div class="fl w-10 pa2 b">
          Info
        </div>
        <div class="fl w-40 pa2 b">
          Sites
        </div>
        <div class="fl w-20 pa2 b">
          Actions
        </div>
      </div>
    </div>
  <% @site_groups.each do |sg| %>
    <div class="mw9 center ph3-ns">
      <div class="cf ph2-ns pv2 mv2 ">
        <div class="fl w-10 pa2">
          <%= sg.name %>
        </div>
        <div class="fl w-10 pa2">
          <%= sg.identifier %>
        </div>
        <div class="fl w-40 pa2 bb b--light-gray">
          <% if sg.sites.present? %>
            <% sg.sites.each do |site| %>
              <span><%= link_to site.name, admin_site_path(site) %></span><br/>
            <% end %>
          <% end %>
        </div>
        <div class="fl w-20 pa2">
          <%= link_to 'Edit', edit_admin_site_group_path(sg) %><br/>
          <%= link_to "Delete", admin_site_group_path(sg), method: :delete, data: { confirm: "Are you sure? This cannot be reversed" } %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
No site groups present
<% end %>


<% if admin? %>
  <%= link_to 'New Site Group', new_admin_site_group_path %>
<% end %>

app/views/admin/site_groups/new.html.erb
<h1>New Site Group</h1>

<%= form_with(model: @site_group, url: admin_site_groups_path) do |form| %>
  <%= render 'form', form: form, site: @site_group %>
<% end %>


<%= link_to 'Back', admin_site_groups_path %>