config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'filter_home#index'
  devise_for :users
    
  scope '/admin' do
    get '/', to: 'welcome#index'
    
    
    
    
    
    
    get :zip_images, to: 'image_zip#zip_images'
    get :download_zipped_images, to: 'image_zip#download_zip'
    # post '/sites/csv/results', to: 'csv#results', as: :results
  end
  
  # todo - will slowly be moving controllers from scope to namespace
  namespace :admin do
    resources :bulk_upload, only: [:index, :create]
    resources :drop_upload, only: [:index, :create]
    resources :results
    resources :types
    resources :site_groups
    resources :submissions
    resources :report_upload
    resources :sites do
      resources :submissions
      resources :registrations
    end

    # reporting
    get :participant_report, to: 'csv#participant_report'
    get :basic_submission_report, to: 'csv#basic_submission'
    get :site_specific_time_period_report, to: 'csv#site_specific_time_period'
    get :site_specific_tags_report, to: 'csv#site_specific_tags'
    get :tag_specific_report, to: 'csv#tags_report'
    get :image_quality_report, to: 'csv#image_quality'
  end
  
  # API  
  namespace :api do
    namespace :v1 do
      resources :submissions
      get :submission_data, to: 'submissions#data'
      get :zip_images, to: 'zip#zip_images'
    end
  end
end

app/models/submission.rb
class Submission < ApplicationRecord
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  belongs_to :site
  has_one :type,  :dependent => :destroy
  accepts_nested_attributes_for :type
  belongs_to :participant
  
  validate :validate_site_id
  validate :validate_participant_id
  validates_presence_of :record_taken
  validates :image, presence: true

  has_one_attached :image
  # to get url for image when developing API - use s.image.service_url
  TYPE_NAMES = %w(EMAIL TWITTER WHATSAPP INSTAGRAM OTHER )

  scope :reliable, -> { where(reliable: true) }
  
  scope :exclude_unsorted, ->(id) { 
    where.not(site_id: id)
  }

  scope :search_site, ->(site_id) {
    if site_id.present?
      where(site_id: site_id)
    end
  }

  scope :type_search, ->(type_name) {
    if type_name.present?
      type_name.upcase!
      where(type_name:  type_name)
    end
  }

  scope :with_tags, ->(tags) { 
    if tags.present?
      tags = tags.split(',')
      tagged_with(tags, any: true) 
    end
  }
  
  def site_name
    @site_name ||= site.name
  end

  def image_url
    Rails.application.routes.url_helpers.rails_blob_path(image.attachment, only_path: true)
  end
  
  def set_filename
    if self.image.attached?
      file_name = "#{self.id}_#{self.record_taken.strftime("%d-%m-%Y")}_#{type_name.first.downcase}.jpg"
      self.image.blob.update(filename: file_name)
    end
  end
  private

  def validate_site_id
    errors.add(:site_id, "site id is invalid") unless Site.exists?(self.site_id)
  end

  def validate_participant_id
    errors.add(:participant_id, "participant is invalid or missing") unless Participant.exists?(self.participant_id)
  end
end

app/controllers/admin/submissions_controller.rb
# frozen_string_literal: true
module Admin
  class SubmissionsController < ApplicationController
    include SmartListing::Helper::ControllerExtensions
    helper  SmartListing::Helper
    before_action :set_submission, only: %i[show edit update destroy]
    before_action :redirect_unless_admin
    respond_to :js, only: :create
    
    def index
      # NOTE - this method not currently used
      submissions_scope == Submission.with_attached_image.includes([:site, :taggings, image_attachment: :blob])

      submissions_scope = search_site(submissions_scope, p_params[:site_filter]) if p_params[:site_filter].present?
      submissions_scope = submissions_scope.type_search(p_params[:type_filter]) if p_params[:type_filter].present?
      submissions_scope = submissions_scope.tagged_with(p_params[:tag]) if p_params[:tag].present?

      @submissions = smart_listing_create(:submissions, submissions_scope, partial: 'admin/submissions/list')
    end

    def show
      @submission = Submission.find(params[:id])
    end

    def edit; end

    def update
      @submission.update(submission_params)
      respond_to do |format|
        format.js { render 'admin/submissions/update.js.erb' }
        format.html { render 'admin/submissions/update.js.erb'}
      end
    end

    def new
      @submission = Submission.new(site_id: params[:site_id])
      @submission.build_type
      @presenter = ::Registrations::BasePresenter.new(@submission, view_context)
    end

    def create; end

    def destroy
      site = @submission.site
      @submission.destroy
      redirect_to admin_site_path(site.id)
    end

    private

    def p_params
      params.permit(:reliable,
                    :site_id,
                    :site_filter,
                    :type_filter,
                    :tag,
                    :bespoke_size,
                    :page)
    end

    def reliable?
      p_params[:reliable] == 'true'
    end

    def set_submission
      @submission = Submission.find(params[:id])
    end

    def submission_params
      params.require(:submission).permit(:reliable,
                                         :site_id,
                                         :type_id,
                                         :image,
                                         :record_taken,
                                         :submitted_at,
                                         :tag_list)
    end

    def search_site(collection, name)
      collection.where(site_id: Site.find_by(name: name))
    end
  end
end

app/controllers/api/v1/submissions_controller.rb
module Api
  module V1
    class SubmissionsController < BaseController

      def index
        submissions_scope ||= reliable? ? scope.reliable : scope

        unsorted_sites.each do |id|
          submissions_scope = submissions_scope.exclude_unsorted(id)
        end

        paginate json: submissions_scope.order(record_taken: :desc), per_page: page_size
      end

      def data
        # TODO - add some specs you lazy sod.
        date = (Date.today - 1.year).beginning_of_month

        submissions ||= scope_without_images(date)
        submissions_data = SubmissionsDataCreateService.new(submissions, Date.today - 1.year).create
        render json: submissions_data
      end

      private

        def scope
          Submission.with_attached_image.includes([:site, :taggings, image_attachment: :blob]).search_site(site_filter).type_search(type_filter).with_tags(tag_filter)
        end

        def scope_without_images(date)
          Submission.where('record_taken >= ?', date).search_site(site_filter).type_search(type_filter).with_tags(tag_filter)
        end

        def permitted_params
          params.permit(:reliable, 
                        :site_id,
                        :site_filter,
                        :type_filter,
                        :tags,
                        :bespoke_size,
                        :page,
                        :pagination)
        end

        def page_size
          params[:bespoke_size] || (params[:page] && params[:page][:size]) || 10
        end

        def paginate?
          permitted_params[:pagination] == "true"
        end

        def reliable?
          permitted_params[:reliable] == "true"
        end

        def site_filter
          Site.find_by(name: permitted_params[:site_filter]).id if permitted_params[:site_filter].present?
        end

        def type_filter
          permitted_params[:type_filter]
        end

        def tag_filter
          permitted_params[:tags]
        end
        
        def unsorted_sites
          @unsorted_sites||= Site::UNSORTED_SITES.map {|name| Site.find_by(name: name).try(:id) }
        end
    end
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper
  before_action :set_submission, only: [:show, :edit, :update, :destroy]
  before_action :redirect_unless_admin

  def index
    submissions_scope ||= reliable? ? Submission.with_attached_image.reliable : Submission.with_attached_image

    submissions_scope = search_site(submissions_scope, p_params[:site_filter]) if p_params[:site_filter].present?
    submissions_scope = type_search(submissions_scope, p_params[:type_filter]) if p_params[:type_filter].present?
    submissions_scope = submissions_scope.tagged_with(p_params[:tag]) if p_params[:tag].present?

    @submissions = smart_listing_create(:submissions, submissions_scope, partial: "submissions/list")
  end

  def show
    @submission = Submission.find(params[:id])
  end

  def edit
  end

  def update
    @submission.update_attributes(submission_params)
    respond_to do |format|  
      format.js { render 'submissions/update'}
    end  
  end

  def new
    @submission = Submission.new(site_id: params[:site_id])
    @submission.build_type
    @presenter = ::Registrations::BasePresenter.new(@submission, view_context)
  end
  
  def create
  end

  def destroy
    @submission.destroy
  end
  
  private
  
  def p_params
    params.permit(:reliable, 
                  :site_id,
                  :site_filter,
                  :type_filter,
                  :tag,
                  :bespoke_size,
                  :page)
  end

  def reliable?
    p_params[:reliable] == "true"
  end

  def set_submission
    @submission = Submission.find(params[:id])
  end

  def submission_params
    params.require(:submission).permit(:reliable, 
                                       :site_id,
                                       :type_id,
                                       :image, 
                                       :record_taken, 
                                       :submitted_at,
                                       :tag_list,
    )
  end

  def search_site(collection, name)
    collection.where(site_id: Site.find_by(name: name))
  end
  
  def type_search(collection, type_name)
    type_name.upcase!
    collection = collection.joins(:type).where(types: { name: type_name})
    collection
  end

end

app/views/admin/submissions/_form.html.haml
%td{colspan: 8}
  = form_for object, url: site_submission_path(object.site_id, object.id),  multipart: true, remote: true, html: {class: "form-horizontal"} do |f|
    %div.submission-form
      %span.submission
        %img{:src => "#{}"}/

      %span
        =# f.label :url, "URL #{object.errors['url'][0]}"
        =# f.text_field :url
  
      %span
        = f.label :image 
        = f.file_field :image
  
      %span
        = f.label :site_id, "Site #{object.site.name}"
        = f.select :site_id,   options_for_select(Site.all.map {|s| [s.name, s.id]}, [object.site.name, object.site.id] || "")
  
      %span
        = f.label :reliable?, "Reliable / useful? #{object.errors['reliable'][0]}"
        = f.check_box :reliable
  
      %span
        = f.label :record_taken, "date taken #{object.errors['record_taken'][0]}"
        = f.date_field :record_taken
  
      = f.submit "Save"
      %button.cancel Cancel

app/views/admin/submissions/_list.html.haml
- unless smart_listing.empty?
  %table.table.table-striped
    %thead
      %th{scope: "col"}= "Site"
      %th{scope: "col"}= "Image"
      %th{scope: "col"}= "Reliable"
      %th{scope: "col"}= "Type"
      %th{scope: "col"}= "Comments"
      %th{scope: "col"}= "Tags"
      %th{scope: "col"}= smart_listing.sortable "Record taken", "record_taken"
      %th{scope: "col"}= "Actions"
      
    %tbody
      - smart_listing.collection.each do |o|
        %tr
        = smart_listing.render object: o, partial: "admin/submissions/submission", locals: {object: o}

          
  %div.smart-listing-new-button

  = smart_listing.paginate
  = smart_listing.pagination_per_page_links

- else
  %p.warning No records!

app/views/admin/submissions/_submission.html.haml
- cache object do
  %td.table-text= object.site_name
  %td.table-text.image
    -# TODO: refactor this with presenter
    = image_tag(url_for(object.image.variant(resize:"200x200")))
  
  %td.table-text= object.reliable
  %td.table-text= object.type_name
  %td.table-text= object.comment
  %td.table-text= object.tag_list
  %td.table-text= object.record_taken.to_date.strftime "%d/%m/%y" if object.record_taken

  -# - if admin?
  -# These actions don't work, so they have been disabled. This whole view is pretty pointless really...
  -#   %td.actions= smart_listing_item_actions [{name: :show, url: submission_path(object)}, {name: :edit, url: edit_submission_path(object)}, {name: :destroy, url: submission_path(object), confirmation: "Are you sure you want to delete this submission?"}]
  -# - else
  %td.actions= smart_listing_item_actions [{name: :show, url: admin_submission_path(object)}]

app/views/admin/submissions/destroy.js.erb
# not currently used
<%= smart_listing_item :submissions, :destroy, @submission %>

app/views/admin/submissions/edit.js.erb
# not currently used
<%= smart_listing_item :submissions, :edit, @submission, "admin/submissions/form" %>

app/views/admin/submissions/index.html.haml
%div
  %h1= "Submissions"
  %p= "Browse through and filter all the submissions to date"
  = smart_listing_controls_for(:submissions, {class: ""}) do
    .checkbox
      %label.checkbox.inline
        = hidden_field_tag :reliable, "0"
        = check_box_tag :reliable
        = "Reliable?"

    %div.filter.form-search
      .input-group
        = text_field_tag :site_filter, '', class: "submission-options", placeholder: "Search Site", autocomplete: :off, value: "#{params[:site_filter]}"
        %span.input-group-btn

    %div.filter.form-search
      .input-group
        = text_field_tag :type_filter, '', class: "submission-options", placeholder: "Search Type", autocomplete: :off, value: "#{params[:type_filter]}"
        %span.input-group-btn
    
    %div.filter.form-search
      - tags = ActsAsTaggableOn::Tag.all.map {|t| t.name}.uniq
      = select_tag :tag, options_for_select(tags), :include_blank => true, class: 'tag-select'

  %script(type="text/javascript")
    - if params[:f]
      - params[:f].each do |field, param|
        - param.each do |option, value|
          - if value[:o] != "skip"
            - if value[:v].is_a? Hash
              value = ["#{value[:v]['0']}", "#{value[:v]['1']}", "#{value[:v]['2']}"]
            - else
              value = "#{value[:v]}"
              $.filters.append(humanize("#{field}"), "#{field}", "#{Submission.columns_hash[field].type}", value, "#{value['o']}", "", "#{option}");

  = smart_listing_render :submissions

  %br

  -# = link_to "View JS CSV", {}, :class => "js-csv"

app/views/admin/submissions/index.js.erb
<%= smart_listing_update(:submissions) %>

app/views/admin/submissions/show.html.erb
<div class="row show-view">
  <div class="eight columns">
    <%= image_tag(url_for(@submission.image)) %>
  </div>

  <div class="four columns">
    <ul>
      <li>
        <strong>Site</strong>
        <%= @submission.site.name %>
      </li>
      <li>
        <strong>Date taken</strong>
        <%= @submission.record_taken.to_date.strftime "%d/%m/%y" %>
      </li>
      <li>
        <strong>Reliable?</strong>
        <%= @submission.reliable %>
      </li>
      <li>
        <strong>Source</strong>
        <%= @submission.type_name %>
      </li>
    </ul>
  </div>
</div>

<%#= link_to 'Edit', edit_submission_path(@submission) %>
<%= link_to 'Back', admin_submissions_path %>

app/views/admin/submissions/submission.js.erb
<%# Render list for XHR requests %>
<%= smart_listing_update :submissions %>

app/views/admin/submissions/update.js.erb
$("input.<%= @submission.id %>").eq(0).css({"background-color": "green"});
$("input[name=commit].<%= @submission.id %>").eq(0).attr('value', "Submission Updated")
 